#!/usr/bin/env node
/**
 * GENERATED by scripts/export-cad-engine.mjs in the Axle Keys repository. Do not hand-edit —
 * changes are made upstream and re-exported (this repo is a build output, not a fork).
 *
 * Run it with:  npm test
 */
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const CLI = "packages/engine/cli.mjs";

let failed = 0;
const pass = (m) => console.log(`  ok    ${m}`);
const fail = (m) => { failed++; console.error(`  FAIL  ${m}`); };

// ⚠⚠ THE CLI EXITS 1 WHEN A VERDICT FAILS — which is correct, and which leg 2 provokes ON
// PURPOSE. So a non-zero exit is an expected path here, not a crash: the verdict JSON is still
// on stdout, and reading it only from the success branch made the control leg report "could not
// be run" for a model that ran perfectly. Distinguish the two by whether stdout is JSON.
const build = (modelPath, params = []) => {
  const flags = params.map((p) => ` --param "${p}"`).join("");
  try {
    return JSON.parse(execSync(`node ${CLI} build "${modelPath}" --json${flags}`, { cwd: ROOT, encoding: "utf8", stdio: "pipe" }));
  } catch (e) {
    const out = (e.stdout ?? "").toString().trim();
    if (out.startsWith("{")) return JSON.parse(out);   // a failing verdict, which is still a verdict
    throw e;                                            // a real crash
  }
};

console.log("\nAxle Keys cad-engine — verifying this copy\n");

// ── leg 1: every shipped example gives the verdict its README row claims ─────
// The first row is the README's own first command. The rest are the examples table, each a
// fixture with an expected verdict — clean, or a named rule — and each `try` is the --param
// the README invites you to run, with the rule it must produce. Generated from the same list
// the README is rendered from, so a row cannot claim what this does not check.
const EXAMPLES = [
  {
    "file": "examples/side-table.js",
    "expect": "clean"
  },
  {
    "file": "examples/bookshelf-3-shelf.js",
    "expect": "clean"
  },
  {
    "file": "examples/dado-joint.js",
    "expect": "clean"
  },
  {
    "file": "examples/dado-interference.js",
    "expect": {
      "reports": "part_interference"
    }
  },
  {
    "file": "examples/drawer-box.js",
    "expect": "clean",
    "try": {
      "params": [
        "clearance=-1"
      ],
      "expect": {
        "reports": "part_interference"
      }
    }
  },
  {
    "file": "examples/slat-bench.js",
    "expect": "clean",
    "try": {
      "params": [
        "slatPitch=160"
      ],
      "expect": {
        "reports": "unsupported_part"
      }
    },
    "sweep": {
      "args": [
        "--range",
        "slatPitch=70:170:10",
        "--require",
        "passed",
        "--score",
        "max:slatPitch"
      ],
      "expect": {
        "winner": {
          "slatPitch": 150
        },
        "firstExcluded": {
          "slatPitch": 160,
          "reports": "unsupported_part"
        }
      }
    }
  }
];
console.log("1. every example gives the verdict its README row claims");
// A row's `sweep` is the README's real `axle sweep` run: re-run here with --json and read by
// the SAME checkSweep the exporter asserted it with at render time, so the README, this test
// and the source cannot disagree about which variant won and which was the first refused.
const sweep = (modelPath, args) => {
  const cmd = `node ${CLI} sweep "${modelPath}" ${args.map((a) => `"${a}"`).join(" ")} --json`;
  try {
    return execSync(cmd, { cwd: ROOT, encoding: "utf8", stdio: "pipe" });
  } catch (e) {
    const out = (e.stdout ?? "").toString().trim();
    if (out.startsWith("{")) return out;   // exit 1 = nothing survived the filters, still JSON
    throw e;
  }
};
function checkSweep(ndjson, expect) {
  const lines = ndjson.trim().split("\n").filter(Boolean).map((l) => JSON.parse(l));
  const summary = lines[lines.length - 1]?.summary;
  if (!summary) return { ok: false, why: "the sweep printed no { summary } line" };
  const rows = lines.slice(0, -1);
  const same = (a, b) => Object.keys(b).every((k) => a?.[k] === b[k]);
  const show = (p) => Object.entries(p ?? {}).map(([k, v]) => `${k}=${v}`).join(" ");
  if (!summary.winner) return { ok: false, why: `no variant survived the filters (${summary.ranked} ranked of ${summary.variants}) — expected the winner ${show(expect.winner)}` };
  if (!same(summary.winner.params, expect.winner)) return { ok: false, why: `the winner is ${show(summary.winner.params)}, but the row claims ${show(expect.winner)}` };
  const excluded = rows.filter((r) => r.rank == null).sort((a, b) => a.index - b.index);
  const first = excluded[0];
  if (!first) return { ok: false, why: `nothing was excluded, but the row claims the first exclusion is ${show(expect.firstExcluded)}` };
  const { reports, ...firstParams } = expect.firstExcluded;
  if (!same(first.params, firstParams)) return { ok: false, why: `the first excluded variant is ${show(first.params)}, but the row claims ${show(firstParams)}` };
  if (reports && !(first.problems ?? []).some((p) => p.rule === reports && !p.unverified)) return { ok: false, why: `the first excluded variant (${show(first.params)}) did not report ${reports}: ${JSON.stringify((first.problems ?? []).map((p) => p.rule))}` };
  return { ok: true, winner: summary.winner.params, first: first.params, excluded: excluded.length, ranked: summary.ranked };
}
const expectVerdict = (label, v, expect) => {
  if (!v.ok) return fail(`${label} did not build: ${v.error}`);
  if (!v.parts?.length) return fail(`${label} produced no parts`);
  if (expect === "clean") {
    if (!v.passed) return fail(`${label} was expected clean but reported: ${JSON.stringify((v.problems ?? []).map((p) => p.rule))}`);
    return pass(`${label} — ${v.parts.length} parts, verdict clean`);
  }
  if (v.passed) return fail(`${label} was expected to report ${expect.reports} but came back clean — the check is not firing`);
  const hit = (v.problems ?? []).find((p) => p.rule === expect.reports && !p.unverified);
  if (!hit) return fail(`${label} failed, but not for ${expect.reports}: ${JSON.stringify((v.problems ?? []).map((p) => p.rule))}`);
  return pass(`${label} — ${expect.reports} reported, as the README says`);
};
for (const ex of EXAMPLES) {
  try {
    expectVerdict(ex.file, build(ex.file), ex.expect);
    if (ex.try) expectVerdict(`${ex.file} --param ${ex.try.params.join(" ")}`, build(ex.file, ex.try.params), ex.try.expect);
    if (ex.sweep) {
      const label = `${ex.file} sweep ${ex.sweep.args.join(" ")}`;
      const got = checkSweep(sweep(ex.file, ex.sweep.args), ex.sweep.expect);
      const show = (p) => Object.entries(p ?? {}).map(([k, v]) => `${k}=${v}`).join(" ");
      if (!got.ok) fail(`${label}: ${got.why}`);
      else pass(`${label} — sweep winner ${show(got.winner)}, first excluded ${show(got.first)} (${ex.sweep.expect.firstExcluded.reports}), as the README shows`);
    }
  } catch (e) {
    fail(`${ex.file}: ${CLI} threw: ${(e.stderr || e.message).toString().slice(-400)}`);
  }
}

// ── leg 2: POSITIVE CONTROL — the checks are alive, not silently dead ────────
// Two 50mm cubes offset 25mm on X share exactly 25 x 50 x 50 = 62,500mm3 of solid volume.
// If this model comes back clean, the check surface is not running and every clean verdict
// this package gives you is worthless. That is why the failing case is tested, not just the
// passing one.
console.log("2. the checks can still fail");
const fixture = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "axle-verify-")), "overlap.js");
try {
  fs.writeFileSync(fixture, [
    "const main = ({ makeBaseBox }) => {",
    "  const a = makeBaseBox(50, 50, 50);",
    "  const b = makeBaseBox(50, 50, 50).translateX(25);",
    '  return [{ name: "A", shape: a }, { name: "B", shape: b }];',
    "};",
    "",
  ].join("\n"));
  const v = build(fixture);
  if (!v.ok) fail(`the control model did not build at all: ${v.error}`);
  else if (v.passed) fail("two parts sharing 62,500mm3 of solid volume PASSED — the checks are not running, so no clean verdict from this copy means anything");
  else {
    const hit = (v.problems ?? []).find((p) => p.rule === "part_interference");
    if (!hit) fail(`the control failed, but not for the expected reason — no part_interference in ${JSON.stringify((v.problems ?? []).map((p) => p.rule))}`);
    else pass("part_interference reported on the control — the measured-intersection check is live");
  }
} catch (e) {
  fail(`the control could not be run: ${(e.stderr || e.message).toString().slice(-400)}`);
} finally {
  try { fs.rmSync(path.dirname(fixture), { recursive: true, force: true }); } catch {}
}

// ── the ceiling, stated ──────────────────────────────────────────────────────
console.log(`
This proves your copy RUNS, that every example gives the verdict its README row
claims, and that the checks are ALIVE. It does not contact
axlekeys.com, so it does not measure agreement with the hosted verdict — that rests
on this package being generated from the same source the platform runs, not on
anything this script observed.`);

if (failed) {
  console.error(`\n${failed} check(s) FAILED — this copy is not sound. Please open an issue at
https://github.com/AxleKeys/cad-engine/issues with the output above.\n`);
  process.exit(1);
}
console.log("\nAll checks passed.\n");
